### ISSUE TITLE
Clearer documentation about kernel in the holiday feature

### ISSUE THREAD

**Issue by alexbacce** [giotto-ai/giotto-time#101]
#### Description

There is a lack of documentation about how the holiday feature is affected by the kernel. A clearer explanation in the documentation would be helpful to let the user understand what is exactly the behaviour.

**Comment by ckae95** [comment]
I would suggest something like this:

> The holiday feature is created by taking the dot product between the kernel and the column which contains a 1 if the corresponding day is a holiday and a 0 if the day is not a holiday. The rolling window has the same size as the kernel and the calculated value of the dot product is divided by the number of holidays in the window to get the value of the holiday feature.
